spring:
  application:
    name: case-study-hotel

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel_management?createDatabaseIfNotExist=true
    username: root
    password: 123456

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        id:
          new_generator_mapping: true
        show_sql: true
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace